# Task Difficulty Guidelines
1.	Routine (DC 0) – Anyone can do this basically every time.
2.	Simple (DC 3) – Most people can do this most of the time.
3.	Standard (DC 6) – Typical task requiring focus, but most people can usually do this.
4.	Demanding (DC 9) – Requires full attention; most people have a 50/50 chance to succeed.
5.	Difficult (DC 12) – Trained people have a 50/50 chance to succeed.
6.	Challenging (DC 15) – Even trained people often fail.
7.	Intimidating (DC 18) – Normal people almost never succeed.
8.	Formidable (DC 21) – Impossible without skills or great effort.
9.	Heroic (DC 24) – A task worthy of tales told for years afterward.
10.	Legendary (DC 27) – A task worthy of legends that last lifetimes.
11.	Impossible (DC 30) – A task that normal humans couldn’t consider (but one that doesn’t break the laws of physics).

# Opposed Checks
- Notice a trap: Perception vs. Trap’s detection DC
- Sneak up to or hide from a creature: Stealth vs. Perception
- Hide an object on your person: Sleight of Hand vs. Perception
- Steal a key from a chain: Sleight of Hand vs. Insight
- Tell a lie: Deception vs. Insight
- Pass off a forged document: Forgery Kit vs. Investigation
- Treat a disease or poison: Medicine vs. Disease or poison’s save DC
- Grapple or wrestle a creature: Athletics vs. Athletics or Acrobatics