{
    {
        "Description": "Routine",
        "DC": 0,
        "Guidance": "Anyone can do this basically every time."
    },
    {
        "Description": "Simple",
        "DC": 3,
        "Guidance": "Most people can do this most of the time."
    },
    {
        "Description": "Standard",
        "DC": 6,
        "Guidance": "Typical task requiring focus, but most people can usually do this."
    },
    {
        "Description": "Demanding",
        "DC": 9,
        "Guidance": "Requires full attention; most people have a 50/50 chance to succeed."
    },
    {
        "Description": "Difficult",
        "DC": 12,
        "Guidance": "Trained people have a 50/50 chance to succeed."
    },
    {
        "Description": "Challenging",
        "DC": 15,
        "Guidance": "Even trained people often fail."
    },
    {
        "Description": "Intimidating",
        "DC": 18,
        "Guidance": "Normal people almost never succeed."
    },
    {
        "Description": "Formidable",
        "DC": 21,
        "Guidance": "Impossible without skills or great effort."
    },
    {
        "Description": "Heroic",
        "DC": 24,
        "Guidance": "A task worthy of tales told for years afterward."
    },
    {
        "Description": "Legendary",
        "DC": 27,
        "Guidance": "A task worthy of legends that last lifetimes."
    },
    {
        "Description": "Impossible",
        "DC": 30,
        "Guidance": "A task that normal humans couldn\u2019t consider (but one that doesn\u2019t break the laws of physics)."
    }
}